### ISSUE TITLE
`uuid.UUID.Value` panics with nil pointers

### ISSUE THREAD

**Issue by abdusco** [gofrs/uuid#107]
`uuid.UUID.Value` is not implemented with pointer receiver,
therefore it panics when passing nil values to an SQL query.

```
value method github.com/gofrs/uuid/v3.UUID.Value called using nil *UUID pointer
```

**Comment by dylan-bourque** [comment]
This case is why [the `NullUUID` type](https://pkg.go.dev/github.com/gofrs/uuid#NullUUID) exists. It mirrors the behavior of the `Null*` types in the `database/sql` package.

**Comment by cameracker** [comment]
Hi, I believe the API already supports this behavior as of some changes in its latest release. Please let us know if this is still a gap.
