### ISSUE TITLE
Link to new UUID draft

### ISSUE THREAD

**Issue by victoraugustolls** [gofrs/uuid#118]
Hi! First of all, thanks for the library!

AFAIK the new UUID drafts didn't change the ~~uuidv6~~ / uuidv7 implementations, the README could be updated to say that this library is compatible with the most recent draft. WDYT?

Link to the new draft: https://datatracker.ietf.org/doc/html/draft-ietf-uuidrev-rfc4122bis-02

**Edit:** actually it looks like there are some changes to the uuidv6 implementation since the referenced draft in the readme.

**Comment by cameracker** [comment]
Hi, thanks for reporting!  There's a draft PR that applies this change that we're waiting on.

**Comment by victoraugustolls** [comment]
@cameracker There is already a new draft after the one referenced in the pull request 😅! And I do think some changes are needed in the uuidv6 generation, but I need to look closely to be sure!

**Comment by kohenkatz** [comment]
Sorry for the delay on updating the draft PR. 😢

I'm looking into it right now, updating to draft 14.

**Comment by kohenkatz** [comment]
The new RFC has been released! 4122 has been obsoleted by 9562. My Pull Request has been updated to reflect this. Hopefully it will be reviewed and merged soon.
