### ISSUE TITLE
Wrong error message for TimestampFromV7

### ISSUE THREAD

**Issue by PatrLind** [gofrs/uuid#132]
Seems like the UUID library returns the wrong error message for function `TimestampFromV7`.
The returned error message is (with input 'e86160d3-beff-443c-b9b5-1f8197ccb12e':
`uuid: e86160d3-beff-443c-b9b5-1f8197ccb12e is version 4, not version 6`
The expected error message should be:
`uuid: e86160d3-beff-443c-b9b5-1f8197ccb12e is version 4, not version 7`

**Comment by cameracker** [comment]
Hi, this has been closed with #127
