### ISSUE TITLE
Contact people from https://awesome-go.com/

### ISSUE THREAD

**Issue by zerkms** [gofrs/uuid#20]
I think it would be helpful if we contacted https://awesome-go.com/ and explained the situation

This fork should be added with no doubts, but it's not certain to me whether the original one should be marked explicitly somehow.

**Comment by jadr2ddude** [comment]
I have submitted [a pull request for this](https://github.com/avelino/awesome-go/pull/2014).

**Comment by zerkms** [comment]
Probably removing satori's version is too aggressive. May be just add some clarification text additionally to the project description.

**Comment by theckman** [comment]
We should do this once we've cut a release and are feeling good about the README file. Right now this project is only going to be usable by people who use `go get`. Anything dealing with semantic versions is going to pull a broken version of the library.

**Comment by jadr2ddude** [comment]
The PR has been temporarily closed and will be re-opened after we have a release.

**Comment by theckman** [comment]
Removing this from the 2.0.0 milestone, since this is to happen _after_ not before.

**Comment by jadr2ddude** [comment]
I can reopen this tonight

**Comment by theckman** [comment]
@jadr2ddude now that #19 is merged I think you're all good to go.

**Comment by jadr2ddude** [comment]
The awesome-go PR has been merged.
