### ISSUE TITLE
Improve code example in README

### ISSUE THREAD

**Issue by acln0** [gofrs/uuid#26]
The current example should be improved. Currently, that code does not compile, and it executes the final `fmt.Printf("Successfully parsed: %s", u2)` unconditionally.

Aside from that, in the imports, we should add a newline between `"fmt"` and `"github.com/gofrs/uuid"`, since it is customary to separate standard library and third party imports with a blank line.

**Comment by acln0** [comment]
@theckman While we're on the topic of the readme, the license badge seems to be broken. This is what it looks like for me: https://i.imgur.com/MchSzeC.png I don't know if this is a flake, but it's worth investigating. It looks like the license badge was added in https://github.com/gofrs/uuid/commit/6bfd6b443d02801cad5d797345d48eef74d94cb6.

**Comment by jadr2ddude** [comment]
@acln0 I have been debugging, and the license badge does not consistently load. This is a github problem I think. Content loads slowly and occasionally times out.

**Comment by acln0** [comment]
Closed in #28.
