### ISSUE TITLE
Add support for Go 1.11 in travis

### ISSUE THREAD

**Issue by acln0** [gofrs/uuid#45]
When 1.11 is released, we should add support for it to travis, as described in https://github.com/gofrs/uuid/pull/44#issuecomment-415441445.

**Comment by acln0** [comment]
Ping @jadr2ddude if you have the time and are willing.

**Comment by jadr2ddude** [comment]
Waiting on #44

**Comment by theckman** [comment]
@jadr2ddude you should be free to go.

**Comment by jadr2ddude** [comment]
#50 merged
