### ISSUE TITLE
Duplicate with the buffalo fork ?

### ISSUE THREAD

**Issue by flibustenet** [gofrs/uuid#47]
Don't know if you was aware of this fork that i just discover:
https://github.com/gobuffalo/uuid

**Comment by CameronAckermanSEL** [comment]
Last I checked that repo still had the critical vulnerability because it was created from satori/go.uuid@master

**Comment by zerkms** [comment]
That fork had 0 stars and at the moment gofrs fork was created: did not have anything but this change https://github.com/gobuffalo/uuid/commit/4bf3ef4efa68dd27ea50c4c1f49caafe243da8bf

There are number of forks that have nothing-to-almost-nothing changes. In that regard that fork is not unique.
