### ISSUE TITLE
go.mod file does not work correctly yet

### ISSUE THREAD

**Issue by acln0** [gofrs/uuid#51]
We added a `go.mod` in #44, but we did not cut a release after that, which means that the `go.mod` file is not working as expected, unfortunately. Importing `github.com/gofrs/uuid/v3` fails with a pretty cryptic error right now.

We should cut v3.1.1, to make modules work correctly.

Could you please do the honors, @theckman?

EDIT: it was explained to me that the reason it doesn't work is

> because the new tag is still a question to be answered: should it be `v3.1.1` or `v3.2.0` or `v4.0.0`

which makes some sense, I suppose.

**Comment by theckman** [comment]
I'll get to this as soon as I can (next few hours).

**Comment by acln0** [comment]
Probably relevant: https://github.com/golang/go/issues/27432.

I feel like we don't need more than a patch version bump, but that issue is probably worth tracking nevertheless.

**Comment by theckman** [comment]
Fixed with: https://github.com/gofrs/uuid/releases/tag/v3.1.1
>3.1.1: UUIDs for Workgroups

**Comment by theckman** [comment]
(It's a joke)

**Comment by foxcpp** [comment]
`go get` refuses to install 3.1.1:
```
⟩ go get github.com/gofrs/uuid@v3.1.1
go: finding github.com/gofrs/uuid v0.0.0-20180830191909-370558f003bf
go: github.com/gofrs/uuid@v0.0.0-20180830191909-370558f003bf: go.mod has post-v0 module path "github.com/gofrs/uuid/v3" at revision 370558f003bf
go: error loading module requirements
```

Btw, shouldn't go.mod contain `module github.com/gofrs/uuid` without v3 suffix?
