### ISSUE TITLE
Ability to encode specific timestamp into a V1 UUID

### ISSUE THREAD

**Issue by rkuris** [gofrs/uuid#84]
Hi,

I have a need to encode a specific timestamp (instead of time.Now()) into a V1 UUID. There doesn't seem to be a way to do that. Before I start coding the change for that, I'm checking to see if this is something that is generally useful or if I should just maintain my own code to do this.

Thoughts?

**Comment by CameronAckermanSEL** [comment]
This strikes me as a useful bit of functionality and wouldn't be a major expansion to the API. Maybe something like 

`NewV1FromTimestamp(t time.Time)`

**Comment by adiatma85** [comment]
Do we need a function to decode the UUID to got the specific time?

**Comment by cameracker** [comment]
This has been closed  in #142
