### ISSUE TITLE
Why does Timestamp.Time return an error?

### ISSUE THREAD

**Issue by esco** [gofrs/uuid#87]
When parsing a `time.Time` value from a v1 uuid using `UUID.TimestampFromV1`, the `Timestamp.Time` function is called. This function only ever returns a `nil` error. Why does this function have an error for the second return argument when one can't ever be produced?

https://github.com/gofrs/uuid/blob/094e8c20495e85b2066fb9e69159b0f3fc066bca/uuid.go#L72-L85

**Comment by theckman** [comment]
Looks like it was kept in a refactor from an external contribution, and missed in review.

**Comment by zerkms** [comment]
@theckman I asked you about it a year (?) ago (when the project was initially worked) and your response was to have it here just in case if it ever needed to not break the API.

**Comment by theckman** [comment]
I thought that was the case, but couldn't find the conversation so I didn't want to commit to that.

**Comment by esco** [comment]
I see, @theckman would you say it's safe to simply use a [blank identifier](https://golang.org/doc/effective_go.html#blank) for the error value and proceed as if an error isn't possible?

**Comment by theckman** [comment]
@esco I wouldn't be comfortable saying that. Since it wouldn't require an API change, I could see us making a change that could cause that to start returning an error. In that case a minor version upgrade would break your code.

**Comment by esco** [comment]
Makes sense. Thanks for the insight and quick response!

**Comment by CameronAckermanSEL** [comment]
Hi @esco , thank you very much for the question. Its looking like this discussion is resolved (for now) so I'm going to close the issue. If you have anything else you'd like to enquire about this topic please feel free to keep posting! 

Have a good one
